name: Todo-app Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Set up Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: '22'
      - name: Install dependencies and Test
        run: |
          npm install 
#         npm test

  Build_and_Deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push Docker image to Docker Hub
        run: |
          docker build -t richman100/todo-application:latest .
          docker push richman100/todo-application:latest
      - name: Create Dockerrun.aws.json
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "richman100/todo-application:latest",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "3000",
                "HostPort": "80"
              }
            ]
          }' > Dockerrun.aws.json
      - name: Validate Dockerrun.aws.json
        run: |
          cat Dockerrun.aws.json
          python3 -m json.tool < Dockerrun.aws.json
      - name: List files for debugging
        run: ls -la
      - name: Deploy to Elastic Beanstalk 
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: todo-app
          environment_name: Todo-app-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: Dockerrun.aws.json